// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	http "github.com/go-kit/kit/transport/http"
	endpoint "github.com/msegeya56/todo-kit-microsrvice/customer/pkg/endpoint"
	http1 "net/http"
)

// NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := http1.NewServeMux()
	makePostHandler(m, endpoints, options["Post"])
	makeGetAllHandler(m, endpoints, options["GetAll"])
	makeGetByIDHandler(m, endpoints, options["GetByID"])
	makeUpdateHandler(m, endpoints, options["Update"])
	makeGetByDateHandler(m, endpoints, options["GetByDate"])
	makeDeleteHandler(m, endpoints, options["Delete"])
	return m
}
